const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");

const requiredFiles = [
  "UI - html-design-files/Double You Coaching Site Main-design.dc.html",
  "js/support.js",
  "js/image-slot.js",
  "js/site-enhancements.js",
  "vercel.json",
];

const requiredImages = [
  "image-assets/nana-bonsra.png",
  "image-assets/nana-blue.png",
  "image-assets/nana-2.avif",
  "image-assets/images.jpg",
  "image-assets/lotus-silhouette-logo_361591-2211.avif",
  "image-assets/sunday-good-reads.png",
];

const indexMarkers = [
  "dyc-burger",
  "max-width:880px",
  "Beauty",
  "Ashes.",
  "/js/support.js",
  "/js/site-enhancements.js",
  "class Component extends DCLogic",
];

const errors = [];
const warnings = [];

function checkFile(relativePath) {
  const fullPath = path.join(root, relativePath);
  if (!fs.existsSync(fullPath)) {
    errors.push(`Missing required file: ${relativePath}`);
    return false;
  }
  return true;
}

for (const file of requiredFiles) {
  checkFile(file);
}

for (const file of requiredImages) {
  checkFile(file);
}

if (fs.existsSync(path.join(root, "public"))) {
  errors.push(
    'Found a "public/" folder — Vercel will deploy only that directory and skip index.html. Remove it or add public/ to .gitignore.',
  );
}

const indexPath = path.join(root, "index.html");
if (!fs.existsSync(indexPath)) {
  errors.push("index.html was not generated by the build step.");
} else {
  const indexHtml = fs.readFileSync(indexPath, "utf8");
  for (const marker of indexMarkers) {
    if (!indexHtml.includes(marker)) {
      errors.push(`index.html is missing expected content: ${marker}`);
    }
  }

  const slotCount = (indexHtml.match(/<image-slot/g) || []).length;
  const srcCount = (indexHtml.match(/src="\/image-assets\//g) || []).length;
  if (slotCount !== srcCount) {
    warnings.push(
      `Image slots (${slotCount}) and wired image sources (${srcCount}) do not match.`,
    );
  }
}

if (warnings.length) {
  console.warn("Build warnings:");
  for (const warning of warnings) {
    console.warn(`  - ${warning}`);
  }
}

if (errors.length) {
  console.error("Build validation failed:");
  for (const error of errors) {
    console.error(`  - ${error}`);
  }
  process.exit(1);
}

console.log("Build validation passed.");
console.log(`  index.html: ${fs.statSync(indexPath).size} bytes`);
console.log(`  image slots wired: ${(fs.readFileSync(indexPath, "utf8").match(/src="\/image-assets\//g) || []).length}`);
