const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");

const requiredFiles = [
  "UI - html-design-files/Double You Coaching Site Main-design.dc.html",
  "js/support.js",
  "js/image-slot.js",
  "js/site-enhancements.js",
  "vercel.json",
  "package.json",
];

const requiredImages = [
  "image-assets/nana-bonsra.png",
  "image-assets/nana-blue.png",
  "image-assets/nana-2.avif",
  "image-assets/images.jpg",
  "image-assets/lotus-silhouette-logo_361591-2211.avif",
  "image-assets/sunday-good-reads.png",
];

const sectionIds = ["home", "pillars", "pricing", "work", "gallery", "contact"];

const indexMarkers = [
  "dyc-burger",
  "max-width:880px",
  "dyc-price-grid",
  "dyc-bento",
  "Beauty",
  "Ashes.",
  "/js/support.js",
  "/js/site-enhancements.js",
  "class Component extends DCLogic",
  "three@0.172.0",
  "ScrollTrigger.min.js",
  "ScrollToPlugin.min.js",
];

const indexMustNotInclude = [
  "cdn-cgi/l/email-protection",
  "__cf_email__",
  'src="./support.js"',
  'src="image-slot.js"',
];

const errors = [];
const warnings = [];

function checkFile(relativePath) {
  const fullPath = path.join(root, relativePath);
  if (!fs.existsSync(fullPath)) {
    errors.push(`Missing required file: ${relativePath}`);
    return false;
  }
  return true;
}

for (const file of requiredFiles) {
  checkFile(file);
}

for (const file of requiredImages) {
  const fullPath = path.join(root, file);
  if (!fs.existsSync(fullPath)) {
    errors.push(`Missing required image: ${file}`);
    continue;
  }
  if (fs.statSync(fullPath).size === 0) {
    errors.push(`Empty image file: ${file}`);
  }
}

if (fs.existsSync(path.join(root, "public"))) {
  errors.push(
    'Found a "public/" folder — Vercel may deploy only that directory and skip index.html. Remove it.',
  );
}

const vercelConfigPath = path.join(root, "vercel.json");
if (fs.existsSync(vercelConfigPath)) {
  const vercelConfig = JSON.parse(fs.readFileSync(vercelConfigPath, "utf8"));
  if (vercelConfig.outputDirectory === "public") {
    errors.push('vercel.json outputDirectory must not be "public" for this static site.');
  }
  if (!vercelConfig.outputDirectory) {
    warnings.push('vercel.json is missing outputDirectory — Vercel may expect a "public/" folder after npm run build.');
  }
}

const indexPath = path.join(root, "index.html");
if (!fs.existsSync(indexPath)) {
  errors.push("index.html was not generated by the build step.");
} else {
  const indexHtml = fs.readFileSync(indexPath, "utf8");

  for (const marker of indexMarkers) {
    if (!indexHtml.includes(marker)) {
      errors.push(`index.html is missing expected content: ${marker}`);
    }
  }

  for (const forbidden of indexMustNotInclude) {
    if (indexHtml.includes(forbidden)) {
      errors.push(`index.html still contains broken deploy artifact: ${forbidden}`);
    }
  }

  for (const id of sectionIds) {
    if (!indexHtml.includes(`id="${id}"`)) {
      errors.push(`index.html is missing section anchor: #${id}`);
    }
  }

  if (!indexHtml.includes("mailto:crossriva@hotmail.com")) {
    errors.push("index.html is missing hotmail contact link.");
  }
  if (!indexHtml.includes("mailto:crossriva@yahoo.ca")) {
    errors.push("index.html is missing yahoo contact link.");
  }

  const slotCount = (indexHtml.match(/<image-slot/g) || []).length;
  const srcCount = (indexHtml.match(/src="\/image-assets\//g) || []).length;
  if (slotCount !== srcCount) {
    errors.push(
      `Image slots (${slotCount}) and wired image sources (${srcCount}) do not match.`,
    );
  }

  for (const srcMatch of indexHtml.matchAll(/src="(\/image-assets\/[^"]+)"/g)) {
    const assetPath = srcMatch[1].slice(1);
    if (!fs.existsSync(path.join(root, assetPath))) {
      errors.push(`index.html references missing asset: ${srcMatch[1]}`);
    }
  }
}

const enhancementsPath = path.join(root, "js/site-enhancements.js");
if (fs.existsSync(enhancementsPath)) {
  const enhancements = fs.readFileSync(enhancementsPath, "utf8");
  if (!enhancements.includes("ScrollToPlugin")) {
    warnings.push("site-enhancements.js does not reference ScrollToPlugin.");
  }
}

if (warnings.length) {
  console.warn("Build warnings:");
  for (const warning of warnings) {
    console.warn(`  - ${warning}`);
  }
}

if (errors.length) {
  console.error("Build validation failed:");
  for (const error of errors) {
    console.error(`  - ${error}`);
  }
  process.exit(1);
}

console.log("Build validation passed.");
console.log(`  index.html: ${fs.statSync(indexPath).size} bytes`);
console.log(`  image slots wired: ${(fs.readFileSync(indexPath, "utf8").match(/src="\/image-assets\//g) || []).length}`);
console.log(`  sections: ${sectionIds.length}/${sectionIds.length}`);
